language: node_js

branches:
  only:
    - master
    - /^v.*$/

cache:
  directories:
    - node_modules

script:
  - npm run build
  - npm run lint
  - npm run coveralls
  - npm run docs
  - touch docs/.nojekyll
  - cp .npmrc-publish .npmrc

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs
    github_token: $GITHUB_TOKEN
    on:
      branch: master

  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - packages/ash/dist/*.js
      - packages/ash/dist/*.mjs
      - dist/*
    on:
      tags: true

  - provider: script
    script: npm run lerna:publish
    skip_cleanup: true
    on:
      tags: true
