language: node_js

branches:
  only:
    - master
    - /^v.*$/

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run build
  - npm run coveralls
  - npm run docs

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs
    github_token: $GITHUB_TOKEN
    on:
      branch: master

  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - packages/**/dist/*.js
      - packages/**/dist/*.mjs
      - packages/**/dist/*.ts
    on:
      tags: true

  - provider: script
    script: npm run lerna
    skip_cleanup: true
    on:
      tags: true
